[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200